<#
    Generated by Gemini
#>
function Find-GitRepositoryRoot {
    param (
        [Parameter(Mandatory = $true)]
        [string]$FilePath
    )

    if (Test-Path $FilePath -PathType Leaf) {
        $currentPath = (Get-Item $FilePath).DirectoryName
    }
    else {
        $currentPath = $FilePath
    }
    
    while ($null -ne $currentPath) {
        if (Test-Path (Join-Path $currentPath ".git")) {
            return $currentPath
        }
        $currentPath = (Get-Item $currentPath).Parent
    }

    Write-Warning "No Git repository found in the path or its parent directories."
    return $null
}